version: '2'
services:
  app:
    image: prometheus-demo
    ports:
      - 8080
    environment:
      - SPRING_CLOUD_CONSUL_HOST=consul
    depends_on:
      - consul
  lb:
    image: dockercloud/haproxy
    links:
      - app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
  grafana:
    ports:
      - 3000:3000
    volumes:
      - ./grafana/config.ini:/etc/grafana/config.ini
      - ./grafana/conf/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/conf/provisioning/datasources:/etc/grafana/provisioning/datasources
    links:
      - prometheus
    image: grafana/grafana
  prometheus:
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    image: prom/prometheus:v2.2.1
    depends_on:
      - consul
  consul:
    ports:
      - 8500:8500
    image: consul