groups:
- name: business
  rules:
  - alert: HighErrorRate
    expr: sum without (instance)(rate(orders_total{status="failed"}[5m])) > 10.0
    for: 10s
    labels:
      severity: critical
    annotations:
      summary: High error rate